### ISSUE TITLE
Version 1.6.2 depends on non-existant version of tecnickcom/tcpdf:6.2.13

### ISSUE THREAD

**Issue by felixkiss** [Setasign/FPDI-TCPDF#8]
As of right now, the latest version of [tecnickcom/tcpdf on packagist](https://packagist.org/packages/tecnickcom/tcpdf) is 6.2.12

Was 6.2.13 removed by the maintainer?

**Comment by JanSlabon** [comment]
That's very strange as the version exists on GitHub: https://github.com/tecnickcom/TCPDF/releases/tag/6.2.13. So it looks like a sync issue with packagist? Sadly @nicolaasuni had disabled the issue tracker on the repo... you may contact him through info@tecnick.com (I guess), so that he can update the package on packagist.

**Comment by JanSlabon** [comment]
Is fixed, thanks to @nicolaasuni ! -> https://packagist.org/packages/tecnickcom/tcpdf
